# Generated by Django 5.2.17 on 2026-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishjob',
            name='pid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publishjob',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='contentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'site')), fields=('kind',), name='one_site_config'),
        ),
    ]
