# Generated by Django 5.2.17 on 2026-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_publishjob_pid_publishjob_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
